"""add event_timezone

Revision ID: 0cb38d445403
Revises: ad803e9c36ef
Create Date: 2026-01-17 10:38:34.915535

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cb38d445403"
down_revision: Union[str, Sequence[str], None] = "ad803e9c36ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable first
    op.add_column("events", sa.Column("event_timezone", sa.Text(), nullable=True))
    # 2. Populate existing rows
    op.execute("UPDATE events SET event_timezone = 'America/New_York'")
    # 3. Enforce NOT NULL
    op.alter_column("events", "event_timezone", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "event_timezone")
    # ### end Alembic commands ###
