"""course agent update

Revision ID: 3905128935dc
Revises: ddefbea9c09b
Create Date: 2026-01-06 15:13:25.504537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3905128935dc'
down_revision: Union[str, Sequence[str], None] = 'ddefbea9c09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('agent_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_websites',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_run_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('agent_debug', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name='course_websites_agent_run_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_websites_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'url', name='course_websites_course_url_key')
    )
    op.drop_table('category_icals')
    op.add_column('calendar_sources', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('calendar_sources', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_unique_constraint('calendar_sources_category_url_key', 'calendar_sources', ['category_id', 'url'])
    op.drop_column('calendar_sources', 'default_tzid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_sources', sa.Column('default_tzid', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('calendar_sources_category_url_key', 'calendar_sources', type_='unique')
    op.alter_column('calendar_sources', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('calendar_sources', 'notes')
    op.create_table('category_icals',
    sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('calendar_source_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calendar_source_id'], ['calendar_sources.id'], name=op.f('org_icals_calendar_source_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('org_icals_category_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'calendar_source_id', name=op.f('org_icals_pkey'))
    )
    op.drop_table('course_websites')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
