"""avoid duplicate ical import

Revision ID: ad803e9c36ef
Revises: 3905128935dc
Create Date: 2026-01-09 02:25:27.352329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad803e9c36ef'
down_revision: Union[str, Sequence[str], None] = '3905128935dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('calendar_source_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint('events_unique_calendar_uid', 'events', ['calendar_source_id', 'ical_uid'])
    op.create_index(op.f('ix_events_calendar_source_id'), 'events', ['calendar_source_id'], unique=False)
    op.create_foreign_key('events_calendar_source_id_fkey', 'events', 'calendar_sources', ['calendar_source_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_calendar_source_id_fkey', 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_calendar_source_id'), table_name='events')
    op.drop_constraint('events_unique_calendar_uid', 'events', type_='unique')
    op.drop_column('events', 'calendar_source_id')
    # ### end Alembic commands ###
