"""update courses

Revision ID: c0f134426e07
Revises: d2932b3f8a6a
Create Date: 2026-01-02 16:37:47.231474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f134426e07'
down_revision: Union[str, Sequence[str], None] = 'd2932b3f8a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_name', sa.Text(), nullable=False))
    op.add_column('courses', sa.Column('semesters', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'semesters')
    op.drop_column('courses', 'course_name')
    # ### end Alembic commands ###
