"""add uniqueness constraint for location

Revision ID: c83995e192d8
Revises: f80c620f134e
Create Date: 2026-01-03 15:11:45.642903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83995e192d8'
down_revision: Union[str, Sequence[str], None] = 'f80c620f134e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_unique_soc'), 'events', type_='unique')
    op.create_unique_constraint('events_unique_soc', 'events', ['org_id', 'title', 'semester', 'start_datetime', 'end_datetime', 'location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_unique_soc', 'events', type_='unique')
    op.create_unique_constraint(op.f('events_unique_soc'), 'events', ['org_id', 'title', 'semester', 'start_datetime', 'end_datetime'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
