"""added recurrence override

Revision ID: d2932b3f8a6a
Revises: ebed2522d489
Create Date: 2025-12-18 17:56:39.905987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2932b3f8a6a'
down_revision: Union[str, Sequence[str], None] = 'ebed2522d489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrence_overrides',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rrule_id', sa.BigInteger(), nullable=False),
    sa.Column('frequency', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequency_type', create_type=False), nullable=False),
    sa.Column('interval', sa.BigInteger(), nullable=False),
    sa.Column('by_day', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('by_month', sa.SmallInteger(), nullable=True),
    sa.Column('by_month_day', sa.SmallInteger(), nullable=True),
    sa.Column('new_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_title', sa.Text(), nullable=True),
    sa.Column('new_description', sa.Text(), nullable=True),
    sa.Column('new_location', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rrule_id'], ['recurrence_rules.id'], name='recurrence_overrides_rrule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recurrence_overrides_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurrence_overrides')
    # ### end Alembic commands ###
