"""add last_generated_at to rrule

Revision ID: ddefbea9c09b
Revises: c83995e192d8
Create Date: 2026-01-04 00:20:19.646626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddefbea9c09b'
down_revision: Union[str, Sequence[str], None] = 'c83995e192d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurrence_rules', sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurrence_rules', 'last_generated_at')
    # ### end Alembic commands ###
