"""initial schema from production

Revision ID: ebed2522d489
Revises: 654f07c67db9
Create Date: 2025-09-13 13:55:46.636816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebed2522d489'
down_revision: Union[str, Sequence[str], None] = '654f07c67db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crosslist_groups',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='crosslist_groups_pkey')
    )
    op.create_table('organizations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey'),
    sa.UniqueConstraint('name', name='organizations_name_key')
    )
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    sa.UniqueConstraint('name', name='tags_name_key')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clerk_id', sa.Text(), nullable=True),
    sa.Column('fname', sa.Text(), nullable=True),
    sa.Column('lname', sa.Text(), nullable=True),
    sa.Column('calendar_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='Category_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Category_pkey')
    )
    op.create_table('courses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('course_number', sa.Text(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='courses_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='courses_pkey')
    )
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='schedules_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='schedules_pkey')
    )
    op.create_table('synced_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('local_event_id', sa.Text(), nullable=False),
    sa.Column('google_event_id', sa.Text(), nullable=False),
    sa.Column('start', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('end', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='synced_events_user_id_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='synced_events_pkey')
    )
    op.create_table('admins',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='admins_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='admins_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='admins_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'org_id', name='admins_pkey')
    )
    op.create_table('calendar_sources',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fetch_interval_seconds', sa.BigInteger(), server_default=sa.text("'21600'::bigint"), nullable=False),
    sa.Column('deletion_policy', sa.Text(), server_default=sa.text("'mirror'::text"), nullable=False),
    sa.Column('all_day_handling', sa.Text(), server_default=sa.text("'date_only'::text"), nullable=False),
    sa.Column('horizon_days', sa.BigInteger(), server_default=sa.text("'180'::bigint"), nullable=False),
    sa.Column('sync_mode', sa.Text(), server_default=sa.text("'delta'::text"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('default_event_type', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified_hdr', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_owner', sa.Text(), nullable=True),
    sa.Column('default_tzid', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='calendar_sources_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='calendar_sources_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='calendar_sources_pkey')
    )
    op.create_table('course_crosslist',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_crosslist_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['crosslist_groups.id'], name='course_crosslist_group_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='course_crosslist_pkey')
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('user_edited', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ical_uid', sa.Text(), nullable=True),
    sa.Column('ical_sequence', sa.BigInteger(), nullable=True),
    sa.Column('ical_last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurrences_valid_through', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_occurrence_build_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='events_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='events_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.create_table('schedule_categories',
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='schedule_categories_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name='schedule_categories_schedule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'category_id', name='schedule_categories_pkey')
    )
    op.create_table('schedule_orgs',
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='schedule_orgs_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name='schedule_orgs_schedule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'org_id', name='schedule_orgs_pkey')
    )
    op.create_table('academics',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('course_num', sa.Text(), nullable=True),
    sa.Column('course_name', sa.Text(), nullable=True),
    sa.Column('instructors', sa.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='academics_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name='academics_pkey')
    )
    op.create_table('careers',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('registration_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='careers_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name='careers_pkey')
    )
    op.create_table('category_icals',
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('calendar_source_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_source_id'], ['calendar_sources.id'], name='org_icals_calendar_source_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='org_icals_category_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'calendar_source_id', name='org_icals_pkey')
    )
    op.create_table('clubs',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='clubs_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name='clubs_pkey')
    )
    op.create_table('event_occurrences',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('user_edited', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('event_saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('recurrence', sa.Enum('ONETIME', 'RECURRING', 'EXCEPTION', name='recurrence_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='event_occurrences_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_occurrences_event_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='event_occurrences_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='event_occurrences_pkey')
    )
    op.create_table('event_tags',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_tags_event_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='event_tags_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'tag_id', name='event_tags_pkey')
    )
    op.create_table('recurrence_rules',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequency_type'), nullable=False),
    sa.Column('interval', sa.BigInteger(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('by_month', sa.SmallInteger(), nullable=True),
    sa.Column('by_month_day', sa.SmallInteger(), nullable=True),
    sa.Column('by_day', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('orig_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='recurrence_rules_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recurrence_rules_pkey')
    )
    op.create_table('user_saved_events',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('google_event_id', sa.Text(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='user_saved_events_event_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name='user_saved_events_schedule_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_saved_events_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'event_id', name='user_saved_events_pkey'),
    sa.UniqueConstraint('google_event_id', name='user_saved_events_google_event_id_key')
    )
    op.create_table('event_overrides',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rrule_id', sa.BigInteger(), nullable=False),
    sa.Column('recurrence_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_title', sa.Text(), nullable=True),
    sa.Column('new_description', sa.Text(), nullable=True),
    sa.Column('new_location', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rrule_id'], ['recurrence_rules.id'], name='event_overrides_rrule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='event_overrides_pkey')
    )
    op.create_table('recurrence_exdates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rrule_id', sa.BigInteger(), nullable=False),
    sa.Column('exdate', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rrule_id'], ['recurrence_rules.id'], name='recurrence_exdates_rrule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recurrence_exdates_pkey')
    )
    op.create_table('recurrence_rdates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rrule_id', sa.BigInteger(), nullable=False),
    sa.Column('rdate', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rrule_id'], ['recurrence_rules.id'], name='recurrence_rdates_rrule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recurrence_rdates_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurrence_rdates')
    op.drop_table('recurrence_exdates')
    op.drop_table('event_overrides')
    op.drop_table('user_saved_events')
    op.drop_table('recurrence_rules')
    op.drop_table('event_tags')
    op.drop_table('event_occurrences')
    op.drop_table('clubs')
    op.drop_table('category_icals')
    op.drop_table('careers')
    op.drop_table('academics')
    op.drop_table('schedule_orgs')
    op.drop_table('schedule_categories')
    op.drop_table('events')
    op.drop_table('course_crosslist')
    op.drop_table('calendar_sources')
    op.drop_table('admins')
    op.drop_table('synced_events')
    op.drop_table('schedules')
    op.drop_table('courses')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('organizations')
    op.drop_table('crosslist_groups')
    # ### end Alembic commands ###
