"""add uniqueness constraint and semester to events

Revision ID: f80c620f134e
Revises: 7d654afb7791
Create Date: 2026-01-03 13:29:12.370642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80c620f134e'
down_revision: Union[str, Sequence[str], None] = '7d654afb7791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('semester', sa.Text(), nullable=False))
    op.create_unique_constraint('events_unique_soc', 'events', ['org_id', 'title', 'semester', 'start_datetime', 'end_datetime'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_unique_soc', 'events', type_='unique')
    op.drop_column('events', 'semester')
    # ### end Alembic commands ###
